// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZXvxTfisv-qPbtPqpr6-vnQclKHBFgU',
    appId: '1:838905730232:web:1c5483b9c39243a296104d',
    messagingSenderId: '838905730232',
    projectId: 'abbeav-b780c',
    authDomain: 'abbeav-b780c.firebaseapp.com',
    storageBucket: 'abbeav-b780c.firebasestorage.app',
    measurementId: 'G-97SE6QYY0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHehHcu4ZtjhsYMC06Oa8X7wPMhxnvFHs',
    appId: '1:838905730232:android:b8ddeaa564f3fa1696104d',
    messagingSenderId: '838905730232',
    projectId: 'abbeav-b780c',
    storageBucket: 'abbeav-b780c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWy5JxVHSmlond0ZZIxzt_KHH1DRDh4Xg',
    appId: '1:838905730232:ios:30ebb08618eddcf596104d',
    messagingSenderId: '838905730232',
    projectId: 'abbeav-b780c',
    storageBucket: 'abbeav-b780c.firebasestorage.app',
    iosBundleId: 'app.devanios.abbeav',
  );
}
